version: '3.8'

services:
  postgres_data:
    image: postgres:12
    ports:
      - "5432:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    ports:
      - '8888:8888'
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres_data
